apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocalculator-deployment
  labels:
    app: gocalc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gocalc
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gocalc
    spec:
      containers:
      - name: go-calculator
        image: yagojanos/gocalc:1.0
        ports:
        - containerPort: 8080        
